//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLauncher.ClientApps.Winforms.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameLauncher.ClientApps.Winforms.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GameLauncher {
            get {
                object obj = ResourceManager.GetObject("GameLauncher", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Library {
            get {
                object obj = ResourceManager.GetObject("Library", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @GDEF`·�Gl�GPOSG?o$^\��GSUB����HVAR�B��(XEOS/2�/`STAT��m�avarU.`�8cmap�L0 �fvar���p�gaspTglyfoi��B0Z@gvar�9���pM�head��X�6hhea	%|$hmtxH�G,�
        ///tloca޷4q�Dmaxp��\ name����&amp;postx�3��preph��L��������������������h$r_&lt;���U��TB}�����b��ʫȉ�U��ݧ����U�@@�� [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MontaguSlab_Variable {
            get {
                return ResourceManager.GetString("MontaguSlab-Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @GDEFo
        ///��GPOS�^��|�&quot;GSUBS�Zm\l*HVAR-|�&amp;,�OS/2u�^-`STAT������avar����2cmapy�Ҡ4
        ///�fvar��y�l~gaspTglyfc�Vqۤ3�gvar\����head���6hhea		�|$hmtx&gt;�Jv&gt;��locaY �maxp��\ name�Q��postn����xU*preph��L�������uYY	���V���u
        ///��
        ///	R� �( �0*A84�@@#��g_&lt;����Fݜp��V���� [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Montserrat_Variable {
            get {
                return ResourceManager.GetString("Montserrat-Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SplashImage {
            get {
                object obj = ResourceManager.GetObject("SplashImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
